version: '3.8'

services:
  neo4j:
    image: neo4j:5.13-community
    container_name: ironclaude-neo4j
    restart: unless-stopped
    ports:
      - "7476:7474"  # HTTP (avoiding conflict with virtual-tutor on 7475)
      - "7689:7687"  # Bolt (avoiding conflict with virtual-tutor on 7688)
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    environment:
      # Authentication
      - NEO4J_AUTH=neo4j/claudeagents123
      # Memory configuration
      - NEO4J_server_memory_heap_initial__size=512M
      - NEO4J_server_memory_heap_max__size=2G
      - NEO4J_dbms_memory_pagecache_size=1G
      # APOC plugin activation
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc"]
      # Security
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*
      # Logging
      - NEO4J_server_directories_logs=/logs
    healthcheck:
      test: ["CMD", "neo4j", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

volumes:
  neo4j_data:
    driver: local
  neo4j_logs:
    driver: local
  neo4j_import:
    driver: local
  neo4j_plugins:
    driver: local

networks:
  default:
    name: claude-agents-network
    driver: bridge